WebWeatherApi/Models/WeatherData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebWeatherApi.Models
{
    public class WeatherData
    {
        public class Weather
        {
            // 地點
            public string localName { get; set; }
            public List<WeatherContent> Content { get; set; }
        }
        public class WeatherContent
        {
            //天氣敘述
            public string weatherScript { get; set; }

            //降雨機率
            public string pop { get; set; }

            //最低溫
            public string minTem { get; set; }

            //最高溫
            public string maxTem { get; set; }

            //開始日期
            public string beginTime { get; set; }

            //結束日期
            public string endTime { get; set; }
        }
    }
}

WebWeatherApi/Controllers/WeatherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using Newtonsoft.Json;
using System.IO;
using System.Net;
using Newtonsoft.Json.Linq;
using System.Data;
using WebWeatherApi.Models;

namespace WebWeatherApi.Controllers
{
    public class WeatherController : Controller
    {
        // GET: Weather
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetWeather(string Location)
        {
            List<WeatherData.Weather> data = new List<WeatherData.Weather>();
            HttpClient client = new HttpClient();
            string url = "";
            if (string.IsNullOrEmpty(Location))
            {
                url = "https://opendata.cwa.gov.tw/api/v1/rest/datastore/F-C0032-001?Authorization=CWA-BEED2F13-2090-4AA9-A774-7E4AAFB2C306";
            }
            else
            {
                url = "https://opendata.cwa.gov.tw/api/v1/rest/datastore/F-C0032-001?Authorization=CWA-BEED2F13-2090-4AA9-A774-7E4AAFB2C306&locationName=" + Location;
            }
            HttpResponseMessage msg = client.GetAsync(url).Result;
            // 取得JSON的字串
            string jsonAll = msg.Content.ReadAsStringAsync().Result.ToString();
            // 透過JsonConvert.DeserializeObject 將 JSON字串 轉成物件集合
            JObject weathers = JsonConvert.DeserializeObject<JObject>(jsonAll);
            // 將json資料轉變為json array陣列
            JArray arrAll = (JArray)weathers["records"]["location"];
            foreach (JObject m in arrAll)
            {
                List<WeatherData.WeatherContent> content = new List<WeatherData.WeatherContent>();
                content.Clear();
                //72小時資料
                for (int i = 0; i < 3; i++)
                {
                    content.Add(new WeatherData.WeatherContent
                    {
                        weatherScript = m["weatherElement"][0]["time"][i]["parameter"]["parameterName"].ToString(),
                        pop = m["weatherElement"][1]["time"][i]["parameter"]["parameterName"].ToString(),
                        minTem = m["weatherElement"][2]["time"][i]["parameter"]["parameterName"].ToString(),
                        maxTem = m["weatherElement"][4]["time"][i]["parameter"]["parameterName"].ToString(),
                        beginTime = Convert.ToDateTime(m["weatherElement"][0]["time"][i]["startTime"]).ToString("yyyy/MM/dd HH:mm"),
                        endTime = Convert.ToDateTime(m["weatherElement"][0]["time"][i]["endTime"]).ToString("yyyy/MM/dd HH:mm"),
                    });
                }
                data.Add(new WeatherData.Weather
                {
                    localName = (string)m["locationName"],
                    Content=content,
                });
            }
            return Json(JsonConvert.SerializeObject(data));
        }
    }
}

WebWeatherApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的天氣應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的天氣應用程式</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebWeatherApi/Views/Weather/Index.cshtml
<script src="~/Public/vue.js"></script>
@{
    ViewBag.Title = "Index";
}
<div class="col-md-12 col-lg-12 col-xl-12">
    <div id="divThisForm">
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <label class="control-label text-right col-md-4">顯示個別縣市36小時天氣</label>
                    <div class="col-md-8">
                        <select class="form-control custom-select" v-model="location" v-on:change="changeLocation">
                            <option value="">==請選擇==</option>
                            <option v-for="(weather,index) in WeatherInfo" :value="weather.localName">{{weather.localName}}</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">今日天氣</h5>
                    <div class="row">
                        <div class="table-responsive">
                            <div v-if="location==''">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>地點</th>
                                            <th>天氣敘述</th>
                                            <th>最高溫</th>
                                            <th>最低溫</th>
                                            <th>降雨機率</th>
                                            <th>開始日期</th>
                                            <th>結束日期</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr v-for="(weather,index) in WeatherInfo">
                                            <td>{{weather.localName}}</td>
                                            <td>{{weather.Content[0].weatherScript}}</td>
                                            <td>{{weather.Content[0].maxTem}}</td>
                                            <td>{{weather.Content[0].minTem}}</td>
                                            <td>{{weather.Content[0].pop}}</td>
                                            <td>{{weather.Content[0].beginTime}}</td>
                                            <td>{{weather.Content[0].endTime}}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div v-else>
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>地點</th>
                                            <th>天氣敘述</th>
                                            <th>最高溫</th>
                                            <th>最低溫</th>
                                            <th>降雨機率</th>
                                            <th>開始日期</th>
                                            <th>結束日期</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr v-for="(weather,index) in townWeatherInfo">
                                            <td>{{location}}</td>
                                            <td>{{weather.weatherScript}}</td>
                                            <td>{{weather.maxTem}}</td>
                                            <td>{{weather.minTem}}</td>
                                            <td>{{weather.pop}}</td>
                                            <td>{{weather.beginTime}}</td>
                                            <td>{{weather.endTime}}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var appVm;
    $(document).ready(function () {
        InitialForm();
        GetWeather("");
    });
    //建立Vue畫面
    function InitialForm() {
        appVm = new Vue({
            el: "#divThisForm",
            data: {
                WeatherInfo: [],
                townWeatherInfo:[],
                location:'',
            },
            methods: {
                changeLocation: function () {
                    PartGetWeather(this.location);
                },
            }
        });
    }

    function GetWeather() {
        $.ajax({
            url: "@Url.Action("GetWeather", "Weather")",
            type: "POST",
            data: {
                Location: ""
            },
            success: function (data) {
                var result = JSON.parse(data);
                appVm.WeatherInfo = result;
            },
            beforeSend: function () {
                appVm.WeatherInfo = [];
            }
        })
    }

     function PartGetWeather(location) {
        $.ajax({
            url: "@Url.Action("GetWeather", "Weather")",
            type: "POST",
            data: {
                Location: location
            },
            success: function (data) {
                var result = JSON.parse(data);
                appVm.townWeatherInfo = result[0].Content;
            },
            beforeSend: function () {
                appVm.townWeatherInfo = [];
            }
        })
    }
</script>